/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.uefs.ecomp.bazar.Interface;

import br.uefs.ecomp.bazar.model.Produto;
import br.uefs.ecomp.bazar.model.exception.*;
import java.awt.Component;
import java.util.Date;
import java.util.Iterator;
import javax.swing.*;

/**
 *
 * @author Davi
 */
public class CadastroLeilao extends javax.swing.JFrame {
    
    private MainJframe mainframe;
    /**
     * Creates new form Cadastro
     * @param mainframe
     */
    public CadastroLeilao(MainJframe mainframe)
    {
        this.mainframe = mainframe;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupLeilao = new javax.swing.ButtonGroup();
        jPanel = new javax.swing.JPanel();
        lblInicio = new javax.swing.JLabel();
        btnCadastrar = new javax.swing.JButton();
        lblProduto = new javax.swing.JLabel();
        lblPreco = new javax.swing.JLabel();
        lblIncremento = new javax.swing.JLabel();
        lblTermino = new javax.swing.JLabel();
        rbLeilaoManual = new javax.swing.JRadioButton();
        rbLeilaoAutomatico = new javax.swing.JRadioButton();
        rbLeilaoAutoFechado = new javax.swing.JRadioButton();
        cbProdutos = new javax.swing.JComboBox<>();
        inicioSpinner = new javax.swing.JSpinner();
        terminoSpinner = new javax.swing.JSpinner();
        precoSpinner = new javax.swing.JSpinner();
        incrementoSpinner = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro");
        setResizable(false);

        jPanel.setBackground(new java.awt.Color(255, 255, 255));

        lblInicio.setText("Início:");
        lblInicio.setEnabled(false);

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        lblProduto.setText("Produto:");

        lblPreco.setText("Preço minimo:");

        lblIncremento.setText("Incremento:");

        lblTermino.setText("Término");
        lblTermino.setEnabled(false);

        buttonGroupLeilao.add(rbLeilaoManual);
        rbLeilaoManual.setSelected(true);
        rbLeilaoManual.setText("Leilão Manual");
        rbLeilaoManual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbLeilaoManualActionPerformed(evt);
            }
        });

        buttonGroupLeilao.add(rbLeilaoAutomatico);
        rbLeilaoAutomatico.setText("Leilão automático");
        rbLeilaoAutomatico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbLeilaoAutomaticoActionPerformed(evt);
            }
        });

        buttonGroupLeilao.add(rbLeilaoAutoFechado);
        rbLeilaoAutoFechado.setText("Leilão Fechado");
        rbLeilaoAutoFechado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbLeilaoAutoFechadoActionPerformed(evt);
            }
        });

        cbProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbProdutosMouseClicked(evt);
            }
        });
        cbProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbProdutosActionPerformed(evt);
            }
        });

        inicioSpinner.setModel(new javax.swing.SpinnerDateModel());
        inicioSpinner.setEnabled(false);

        terminoSpinner.setModel(new javax.swing.SpinnerDateModel());
        terminoSpinner.setEnabled(false);

        precoSpinner.setModel(new javax.swing.SpinnerNumberModel(0.0d, null, null, 1.0d));
        precoSpinner.setInheritsPopupMenu(true);

        incrementoSpinner.setModel(new javax.swing.SpinnerNumberModel(0.0d, null, null, 1.0d));

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(rbLeilaoManual)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbLeilaoAutomatico)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbLeilaoAutoFechado))
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(inicioSpinner, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCadastrar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbProdutos, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblProduto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblIncremento, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPreco, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTermino, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblInicio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                            .addComponent(terminoSpinner, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                            .addComponent(precoSpinner, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(incrementoSpinner))))
                .addContainerGap(150, Short.MAX_VALUE))
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbLeilaoAutoFechado)
                    .addComponent(rbLeilaoAutomatico)
                    .addComponent(rbLeilaoManual))
                .addGap(18, 18, 18)
                .addComponent(lblProduto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPreco)
                .addGap(10, 10, 10)
                .addComponent(precoSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblIncremento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(incrementoSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblInicio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inicioSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTermino)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(terminoSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCadastrar)
                .addContainerGap(118, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    @Override
    public void addNotify()
    {
        super.addNotify();
        setProdutos();
        
    }
    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
       
       if(rbLeilaoManual.isSelected())
       {
          try
            {
                mainframe.getFacade().cadastrarLeilaoManual((Produto)cbProdutos.getSelectedItem(), (double)precoSpinner.getValue(), (double)incrementoSpinner.getValue());
                //limparCampos();
                JOptionPane.showMessageDialog(null, "Leilão Manual Cadastrado", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                dispose();
            }
            catch (LeilaoNaoCadastrouException e)
            {
                JOptionPane.showMessageDialog(null, e.toString(), "Erro", JOptionPane.ERROR_MESSAGE);
            }
       }
       else if(rbLeilaoAutomatico.isSelected())
       {
          try
            {
                mainframe.getFacade().cadastrarLeilaoAutomatico((Produto)cbProdutos.getSelectedItem(), (double)precoSpinner.getValue(), (double)incrementoSpinner.getValue(),(Date)inicioSpinner.getValue(),(Date)terminoSpinner.getValue());
                //limparCampos();
                JOptionPane.showMessageDialog(null, "Leilão Auutomatico Cadastrado", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                dispose();
            }
            catch (LeilaoNaoCadastrouException e)
            {
                JOptionPane.showMessageDialog(null, e.toString(), "Erro", JOptionPane.ERROR_MESSAGE);
            }
       }
       else if(rbLeilaoAutoFechado.isSelected())
       {
          try
            {
                mainframe.getFacade().cadastrarLeilaoAutomaticoFechado((Produto)cbProdutos.getSelectedItem(), (double)precoSpinner.getValue(), (double)incrementoSpinner.getValue(),(Date)inicioSpinner.getValue(),(Date)terminoSpinner.getValue());
                //limparCampos();
                JOptionPane.showMessageDialog(null, "Leilão Automatico Fechado Cadastrado", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                dispose();
            }
            catch (LeilaoNaoCadastrouException e)
            {
                JOptionPane.showMessageDialog(null, e.toString(), "Erro", JOptionPane.ERROR_MESSAGE);
            }
       }
              
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void rbLeilaoManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbLeilaoManualActionPerformed
        ativarInputs(false);
    }//GEN-LAST:event_rbLeilaoManualActionPerformed

    private void rbLeilaoAutomaticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbLeilaoAutomaticoActionPerformed
        ativarInputs(true);
    }//GEN-LAST:event_rbLeilaoAutomaticoActionPerformed

    private void rbLeilaoAutoFechadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbLeilaoAutoFechadoActionPerformed
        ativarInputs(true);
    }//GEN-LAST:event_rbLeilaoAutoFechadoActionPerformed

    private void cbProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbProdutosActionPerformed
        
    }//GEN-LAST:event_cbProdutosActionPerformed

    private void cbProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbProdutosMouseClicked
      
    }//GEN-LAST:event_cbProdutosMouseClicked

    private void ativarInputs(boolean bool)
    {
        lblInicio.setEnabled(bool);
        lblTermino.setEnabled(bool);
        inicioSpinner.setEnabled(bool);
        terminoSpinner.setEnabled(bool);
        
    }
//    private void limparCampos()
//    {
//        Component[] components = jPanel.getComponents();
//        for (Component component : components)
//        {
//            if (component instanceof JSpinner)
//            {
//                ((JSpinner) component).setValue(null);
//            }
//        }
//    }    
    public void setProdutos()
    {
        DefaultComboBoxModel<Produto> modelProduto = new DefaultComboBoxModel<>();

        Iterator produtosIterator = mainframe.getFacade().listarProdutosCadastrados();
        while (produtosIterator.hasNext()) {
            modelProduto.addElement((Produto)produtosIterator.next());
        }

        cbProdutos.setModel(modelProduto);
    }
    
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.ButtonGroup buttonGroupLeilao;
    private javax.swing.JComboBox<Produto> cbProdutos;
    private javax.swing.JSpinner incrementoSpinner;
    private javax.swing.JSpinner inicioSpinner;
    private javax.swing.JPanel jPanel;
    private javax.swing.JLabel lblIncremento;
    private javax.swing.JLabel lblInicio;
    private javax.swing.JLabel lblPreco;
    private javax.swing.JLabel lblProduto;
    private javax.swing.JLabel lblTermino;
    private javax.swing.JSpinner precoSpinner;
    private javax.swing.JRadioButton rbLeilaoAutoFechado;
    private javax.swing.JRadioButton rbLeilaoAutomatico;
    private javax.swing.JRadioButton rbLeilaoManual;
    private javax.swing.JSpinner terminoSpinner;
    // End of variables declaration//GEN-END:variables
}
